name: soa

networks:
  soa-network:
    driver: bridge

volumes:
  users_postgres_data:
  posts_postgres_data:

services:
  users-postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "users_db"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-network
    ports:
      - "5432:5432"


  posts-postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "posts_db"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - posts_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-network
    ports:
      - "5433:5432"

  api-gateway-service:
    build:
      context: .
      dockerfile: api_gateway_service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - soa-network

  users-service:
    build:
      context: .
      dockerfile: users_service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - soa-network
    depends_on:
      - api-gateway-service
      - users-postgres

